name: puzle
channels:
  - http://ssb.stsci.edu/astroconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - gunicorn
  - flask
  - pyjwt
  - python-dotenv
  - flask-migrate
  - flask-sqlalchemy
  - flask-mail
  - flask-login
  - email_validator
  - flask-bootstrap
  - flask-wtf
  - psycopg2
  - numpy
  - astropy
  - requests
  - ipython
  - pip
  - pip:
      - zort
      - filelock
      - python-dotenv
prefix: /Users/michael/miniconda3/envs/puzle
